[package]
name = "compose"
version = "0.1.0"
authors = ["Sergei Fomin <sergio-dna@yandex.ru>"]
edition = "2021"

[dependencies]
anyhow = "1.0"
structopt = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"